### ISSUE TITLE
Change namespace form cebe\yii2openapi to phpopenapi\yii2openapi or pertinent

### ISSUE THREAD

**Issue by SOHELAHMED7** [php-openapi/yii2-openapi#27]
All classes of this lib have namespace `cebe\yii2openapi\...`

Since the repo https://github.com/cebe/yii2-openapi (archived) is forked to https://github.com/php-openapi/yii2-openapi (this repo, currently maintained), change in namespace is required.

It should be changed to `phpopenapi\yii2openapi\...` or pertinent.

**Comment by cebe** [comment]
This is a massive BC break, even though it sounds logical to do that I would prefer not to.
