### ISSUE TITLE
Add possibility to define ON DELETE and ON UPDATE for relations

### ISSUE THREAD

**Issue by cebe** [php-openapi/yii2-openapi#70]
In some cases I want to define whether a relation has ON DELETE CASCADE or  ON UPDATE CASCADE or other options. 

So I suggest to implement `x-on-delete` and `x-on-update` on relations.

**Comment by SOHELAHMED7** [comment]
Can you please elaborate how does this issue differ from https://github.com/cebe/yii2-openapi/issues/131 ?

**Comment by cebe** [comment]
it does not, for some reason I did not find it in the README. Closed as duplicate :-)
